name: Test-Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # INstall Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '18.x'
    
    # Install the newman command line utility and also install the html reporter
    - name: Install newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-html

    # Make directory to upload the test results
    - name: Make Directory for results
      run: mkdir -p testResults


    # Run the POSTMAN collection
    - name: Run POSTMAN collection
      run: |
       newman run collection.json -r cli,html --reporter-html-export testResults/htmlreport.html 

    # Upload the contents of Test Results directory to workspace
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: testResults
     
